/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDSProxy } from "../IDSProxy";

export class IDSProxy__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDSProxy {
    return new Contract(address, _abi, signerOrProvider) as IDSProxy;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
