/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDssProxyActions } from "../IDssProxyActions";

export class IDssProxyActions__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDssProxyActions {
    return new Contract(address, _abi, signerOrProvider) as IDssProxyActions;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "manager",
        type: "address",
      },
      {
        internalType: "address",
        name: "jug",
        type: "address",
      },
      {
        internalType: "address",
        name: "gemJoin",
        type: "address",
      },
      {
        internalType: "address",
        name: "daiJoin",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "cdp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "wadC",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "wadD",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "transferFrom",
        type: "bool",
      },
    ],
    name: "lockGemAndDraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "manager",
        type: "address",
      },
      {
        internalType: "address",
        name: "gemJoin",
        type: "address",
      },
      {
        internalType: "address",
        name: "daiJoin",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "cdp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "wadC",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "wadD",
        type: "uint256",
      },
    ],
    name: "wipeAndFreeGem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
