/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFeeManager } from "../IFeeManager";

export class IFeeManager__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeManager {
    return new Contract(address, _abi, signerOrProvider) as IFeeManager;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gasConsumed",
        type: "uint256",
      },
    ],
    name: "takeFeeFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
